AllCops:
  TargetRubyVersion: 2.1.5

inherit_from: .rubocop_todo.yml

#######
# WIP These should all go back to defaults at some point
Metrics/AbcSize:
  Max: 22
Metrics/MethodLength:
  Max: 20
Metrics/ClassLength:
  Max: 190

#######
# Finalized settings

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'spec/lib/jenkins_pipeline_builder/compiler_spec.rb'
    - 'spec/lib/jenkins_pipeline_builder/view_spec.rb'
    - 'spec/lib/jenkins_pipeline_builder/pull_request_generator_spec.rb'
    - 'lib/jenkins_pipeline_builder/extensions/**/*'

Style/Documentation:
  Enabled: false

# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/Next:
  Exclude:
    - 'lib/jenkins_pipeline_builder/extensions/**/*'

# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/VariableName:
  Exclude:
    - 'lib/jenkins_pipeline_builder/extensions/**/*'

Style/SymbolProc:
  IgnoredMethods: new

Style/FrozenStringLiteralComment:
  Enabled: false
