#######
# WIP These should all go back to defaults at some point
Metrics/CyclomaticComplexity:
  Max: 9
Metrics/PerceivedComplexity:
  Max: 11
Metrics/MethodLength:
  Max: 30
Metrics/ClassLength:
  Max: 175

#######
# Finalized settings

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'spec/lib/jenkins_pipeline_builder/compiler_spec.rb'
    - 'spec/lib/jenkins_pipeline_builder/view_spec.rb'
    - 'spec/lib/jenkins_pipeline_builder/pull_request_spec.rb'
    - 'spec/lib/jenkins_pipeline_builder/pull_request_generator_spec.rb'
    - 'lib/jenkins_pipeline_builder/extensions/*'

Style/Documentation:
  Enabled: false

# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/Next:
  Exclude:
    - 'lib/jenkins_pipeline_builder/extensions/*'

# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/VariableName:
  Exclude:
    - 'lib/jenkins_pipeline_builder/extensions/*'

Style/SymbolProc:
  IgnoredMethods: new
